bookers/config/routes.rb
Rails.application.routes.draw do


  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'searches#search'
  get 'relationships/create'
  get 'relationships/destroy'

  devise_for :users
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get 'follows' => 'relationships#follows', as: 'follows'
      get 'follower' => 'relationships#followers', as: 'followers'
  end

  resources :books, only: [:show, :index, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

end

bookers/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search_for(content, method)
	if method == 'perfect'
	    Book.where(title: content)
      elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
	end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
    redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

bookers/app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers/app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<% if @book.errors.any? %>
        <div id="error_explanation">
          <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    	<!--<%#= render 'layouts/errors', obj: @book %>-->
  		<%= render 'books/form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

bookers/app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>

      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= render 'books/form', book: @book %>

    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%#= render 'books/index', books: @books %>
            
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
              <td><%= book.body %></td>
              <!--ここからいいね機能-->
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      ♥<%= book.favorites.count %>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      ♡<%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <!--ここまでいいね機能-->
              <!--ここからコメントカウント-->
              <td>
                <p>コメント数： <%= book.book_comments.count %></p>
              </td>
              <!--ここまでコメントカウント-->
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers/app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <!--ここからサブメニュー-->
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @newbook %>
    </div>
    <!--ここまでサブメニュー-->
    <div class='col-md-8 offset-md-1'>
    <!--ここからメインメニュー-->
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>

          <!--ここからいいね機能-->
          <td>
            <% if @book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  ♥<%= @book.favorites.count %>
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  ♡<%= @book.favorites.count %>
                <% end %>
              </p>
            <% end %>
          </td>
          <!--ここまでいいね機能-->

          <!--ここからコメント数表示機能-->
          <td>
            <p>コメント数： <%= @book.book_comments.count %></p>
          </td>
          <!--ここまでコメント数表示機能-->
          <!--ここから削除・編集ボタン表示機能-->
          <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
          <!--ここまで削除・編集ボタン表示機能-->
      <!--ここからコメント表示機能-->
      <% @book.book_comments.each do |book_comment| %>
        <tr>
          <td>
            <%= link_to user_path(book_comment.user_id) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" %></br>
            <%= book_comment.user.name %>
            <% end %>
          </td>
          <td>
            <%= @book_comment.comment %>
          </td>
          <% if book_comment.user == current_user %>
            <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr></br>
      <% end %>

      <!--ここまでコメント表示機能-->

      <!--ここからコメント入力機能-->
      <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
        <%= f.text_area :comment,cols:'90', rows:'5',placeholder: "コメントをここに" %></br>
        <%= f.submit "送信" %>
      <% end %>
      <!--ここまでコメント入力機能-->
      <!--ここまでメインメニュー-->
    </div>
  </div>
</div>